# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'i-scream' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for i-scream
  pod 'Firebase/Core'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SCLAlertView'

end
